# Generated by Django 4.1.7 on 2023-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('credits', models.SmallIntegerField(default=2, verbose_name='课程学分')),
                ('place', models.CharField(max_length=32, verbose_name='上课地点')),
                ('time', models.CharField(max_length=32, verbose_name='上课时间')),
            ],
        ),
    ]
