# Generated by Django 4.1.7 on 2023-06-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherApp', '0003_teacher_gender_alter_teacher_age_alter_teacher_name'),
        ('courseApp', '0002_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacherApp.teacher', verbose_name='任课老师'),
        ),
    ]
