# Generated by Django 4.1 on 2024-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='introduction',
            field=models.CharField(default='xxx', max_length=120, verbose_name='书籍详情'),
        ),
    ]
