# Generated by Django 4.1.7 on 2023-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('acount_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='学生姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, '未知')], null=True, verbose_name='性别')),
                ('place', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在地')),
                ('course', models.ManyToManyField(to='courseApp.course', verbose_name='已选课程')),
            ],
        ),
    ]
