# Generated by Django 4.1.7 on 2023-06-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='性别'),
        ),
    ]
