# Generated by Django 4.1.7 on 2023-06-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherApp', '0002_remove_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, '未知')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='教师姓名'),
        ),
    ]
